title: Zotz's Domain
author: Zotz Ku
email: gku@gmail.com
description: > #
Stories from the Dark
# social links
github_username: Gku10

show_excerpts: true # set to false to remove excerpts on the homepage
