title: Zotz' Reign
author: Gku10
email: gku.mexico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stories from the darkness that emerge to fule nightmares
# social links

show_excerpts: false # set to false to remove excerpts on the homepage
